# golangci-lint configuration for Lexington
run:
  timeout: 5m
  go: "1.23"

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
    ignore-words:
      - dialogue
      - cancelled
  goimports:
    local-prefixes: github.com/lapingvino/lexington
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 120
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gofmt:
    simplify: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - lll
    - goconst
    - funlen

  disable:
    - gochecknoglobals # We have some valid global variables

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
    # Exclude line length check for template strings in LaTeX files
    - path: latex/write\.go
      text: "\\\\newcommand"
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0
