# golangci-lint configuration for Lexington
run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/lapingvino/lexington
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 120
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gofmt:
    simplify: true
  gofumpt:
    extra-rules: true
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals # We have some valid global variables
    - godox # TODOs are fine for now

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo

    # Exclude some checks from testdata
    - path: testdata/
      linters:
        - errcheck
        - gosec

    # Allow long lines in comments
    - source: "^//.*"
      linters:
        - lll

  exclude:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8
    - "G404: Use of weak random number generator"

  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  case-sensitive: false
